### ISSUE TITLE
showBooking API call returns a Type Error if an invalid booking ID is used

### ISSUE THREAD

**Issue by garethmcc** [TourCMS/node-tourcms#8]
Currently I am making a request using the showBooking method of the SDK, and when I pass a valid booking ID, I get a valid response with all the details of the booking as expected. 

However, if I make the same request with a booking ID that does not exist, instead of receiving an error message in the error parameter or just a blank value, the SDK throws a JavaScript Type error because it is trying to retrieve customer information from the response when there isn't any because the booking ID is invalid.

Here is an example of a request that errors (I have obviously replaced my API credentials with placeholders for security purposes):

```
let tourCmsObj = new Tourcms({
  channelId: '111',
  apiKey: 'aaabbbccc',
  marketplaceId: 129
})
tourCmsObj.showBooking({
  bookingId: 'FakeBookingId',
  callback: showBookingResponse => {
    console.log(JSON.stringify(showBookingResponse))
  }
})
```

The error message I receive when running the request:

> TypeError: Cannot read property 'customers' of undefined

The stack trace points to the following line of code:

> node_modules/tourcms/node-tourcms.js:614:31

If you need any more information please feel free to let me know.

**Comment by paulslugocki** [comment]
Thanks Gareth.

**Comment by garethmcc** [comment]
Any word on this fix? This is actually becoming a really big issue for us now.
